// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	TrackName     string                 `protobuf:"bytes,2,opt,name=track_name,json=trackName,proto3" json:"track_name,omitempty"`
	ArtistUuid    string                 `protobuf:"bytes,3,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	ArtistName    string                 `protobuf:"bytes,4,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	AlbumUuid     string                 `protobuf:"bytes,5,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	AlbumName     string                 `protobuf:"bytes,6,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	Explicit      bool                   `protobuf:"varint,7,opt,name=explicit,proto3" json:"explicit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

func (x *Track) GetTrackName() string {
	if x != nil {
		return x.TrackName
	}
	return ""
}

func (x *Track) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *Track) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *Track) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

func (x *Track) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

func (x *Track) GetExplicit() bool {
	if x != nil {
		return x.Explicit
	}
	return false
}

type Artist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistName    string                 `protobuf:"bytes,1,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	Albums        []*Album               `protobuf:"bytes,2,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artist) Reset() {
	*x = Artist{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Artist) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *Artist) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumName     string                 `protobuf:"bytes,1,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	ArtistName    string                 `protobuf:"bytes,2,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	ArtistUuid    string                 `protobuf:"bytes,3,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	Tracks        []*Track               `protobuf:"bytes,4,rep,name=tracks,proto3" json:"tracks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AlbumUuid     string                 `protobuf:"bytes,6,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Album) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

func (x *Album) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *Album) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *Album) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *Album) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Album) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistUuid  string                 `protobuf:"bytes,1,opt,name=playlist_uuid,json=playlistUuid,proto3" json:"playlist_uuid,omitempty"`
	PlaylistName  string                 `protobuf:"bytes,2,opt,name=playlist_name,json=playlistName,proto3" json:"playlist_name,omitempty"`
	OwnerUuid     string                 `protobuf:"bytes,3,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
	OwnerName     string                 `protobuf:"bytes,4,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Tracks        []*Track               `protobuf:"bytes,5,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Playlist) GetPlaylistUuid() string {
	if x != nil {
		return x.PlaylistUuid
	}
	return ""
}

func (x *Playlist) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

func (x *Playlist) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *Playlist) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Playlist) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type GetTrackByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackByIDRequest) Reset() {
	*x = GetTrackByIDRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackByIDRequest) ProtoMessage() {}

func (x *GetTrackByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTrackByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetTrackByIDRequest) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

// так как это будет использоваться только для стриминг сервиса,
// удалил информацию, которая ему не нужна
type GetTrackByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	DurationMs    int32                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackByIDResponse) Reset() {
	*x = GetTrackByIDResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackByIDResponse) ProtoMessage() {}

func (x *GetTrackByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTrackByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetTrackByIDResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetTrackByIDResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type TrackExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackExistsRequest) Reset() {
	*x = TrackExistsRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackExistsRequest) ProtoMessage() {}

func (x *TrackExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackExistsRequest.ProtoReflect.Descriptor instead.
func (*TrackExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *TrackExistsRequest) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

type TrackExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackExistsResponse) Reset() {
	*x = TrackExistsResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackExistsResponse) ProtoMessage() {}

func (x *TrackExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackExistsResponse.ProtoReflect.Descriptor instead.
func (*TrackExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *TrackExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type SearchTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTrackResponse) Reset() {
	*x = SearchTrackResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTrackResponse) ProtoMessage() {}

func (x *SearchTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTrackResponse.ProtoReflect.Descriptor instead.
func (*SearchTrackResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *SearchTrackResponse) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type SearchTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackName     string                 `protobuf:"bytes,1,opt,name=track_name,json=trackName,proto3" json:"track_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTrackRequest) Reset() {
	*x = SearchTrackRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTrackRequest) ProtoMessage() {}

func (x *SearchTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTrackRequest.ProtoReflect.Descriptor instead.
func (*SearchTrackRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *SearchTrackRequest) GetTrackName() string {
	if x != nil {
		return x.TrackName
	}
	return ""
}

func (x *SearchTrackRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchTrackRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistName    string                 `protobuf:"bytes,1,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtistRequest) Reset() {
	*x = SearchArtistRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtistRequest) ProtoMessage() {}

func (x *SearchArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtistRequest.ProtoReflect.Descriptor instead.
func (*SearchArtistRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *SearchArtistRequest) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *SearchArtistRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchArtistRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchArtistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artists       []*Artist              `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtistResponse) Reset() {
	*x = SearchArtistResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtistResponse) ProtoMessage() {}

func (x *SearchArtistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtistResponse.ProtoReflect.Descriptor instead.
func (*SearchArtistResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *SearchArtistResponse) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

var File_proto_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"\xe1\x01\n" +
	"\x05Track\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\x12\x1d\n" +
	"\n" +
	"track_name\x18\x02 \x01(\tR\ttrackName\x12\x1f\n" +
	"\vartist_uuid\x18\x03 \x01(\tR\n" +
	"artistUuid\x12\x1f\n" +
	"\vartist_name\x18\x04 \x01(\tR\n" +
	"artistName\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x05 \x01(\tR\talbumUuid\x12\x1d\n" +
	"\n" +
	"album_name\x18\x06 \x01(\tR\talbumName\x12\x1a\n" +
	"\bexplicit\x18\a \x01(\bR\bexplicit\"T\n" +
	"\x06Artist\x12\x1f\n" +
	"\vartist_name\x18\x01 \x01(\tR\n" +
	"artistName\x12)\n" +
	"\x06albums\x18\x02 \x03(\v2\x11.catalog.v1.AlbumR\x06albums\"\xd1\x01\n" +
	"\x05Album\x12\x1d\n" +
	"\n" +
	"album_name\x18\x01 \x01(\tR\talbumName\x12\x1f\n" +
	"\vartist_name\x18\x02 \x01(\tR\n" +
	"artistName\x12\x1f\n" +
	"\vartist_uuid\x18\x03 \x01(\tR\n" +
	"artistUuid\x12)\n" +
	"\x06tracks\x18\x04 \x03(\v2\x11.catalog.v1.TrackR\x06tracks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x06 \x01(\tR\talbumUuid\"\xbd\x01\n" +
	"\bPlaylist\x12#\n" +
	"\rplaylist_uuid\x18\x01 \x01(\tR\fplaylistUuid\x12#\n" +
	"\rplaylist_name\x18\x02 \x01(\tR\fplaylistName\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x03 \x01(\tR\townerUuid\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x04 \x01(\tR\townerName\x12)\n" +
	"\x06tracks\x18\x05 \x03(\v2\x11.catalog.v1.TrackR\x06tracks\"4\n" +
	"\x13GetTrackByIDRequest\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\"K\n" +
	"\x14GetTrackByIDResponse\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x05R\n" +
	"durationMs\"3\n" +
	"\x12TrackExistsRequest\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\"-\n" +
	"\x13TrackExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"@\n" +
	"\x13SearchTrackResponse\x12)\n" +
	"\x06tracks\x18\x01 \x03(\v2\x11.catalog.v1.TrackR\x06tracks\"a\n" +
	"\x12SearchTrackRequest\x12\x1d\n" +
	"\n" +
	"track_name\x18\x01 \x01(\tR\ttrackName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"d\n" +
	"\x13SearchArtistRequest\x12\x1f\n" +
	"\vartist_name\x18\x01 \x01(\tR\n" +
	"artistName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"D\n" +
	"\x14SearchArtistResponse\x12,\n" +
	"\aartists\x18\x01 \x03(\v2\x12.catalog.v1.ArtistR\aartists2\xd6\x02\n" +
	"\x0eCatalogService\x12Q\n" +
	"\fGetTrackByID\x12\x1f.catalog.v1.GetTrackByIDRequest\x1a .catalog.v1.GetTrackByIDResponse\x12N\n" +
	"\vTrackExists\x12\x1e.catalog.v1.TrackExistsRequest\x1a\x1f.catalog.v1.TrackExistsResponse\x12N\n" +
	"\vSearchTrack\x12\x1e.catalog.v1.SearchTrackRequest\x1a\x1f.catalog.v1.SearchTrackResponse\x12Q\n" +
	"\fSearchArtist\x12\x1f.catalog.v1.SearchArtistRequest\x1a .catalog.v1.SearchArtistResponseB)Z'privy_stream/proto/catalog/v1;catalogv1b\x06proto3"

var (
	file_proto_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_v1_catalog_proto_rawDescData []byte
)

func file_proto_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_v1_catalog_proto_rawDesc), len(file_proto_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_v1_catalog_proto_rawDescData
}

var file_proto_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_catalog_v1_catalog_proto_goTypes = []any{
	(*Track)(nil),                // 0: catalog.v1.Track
	(*Artist)(nil),               // 1: catalog.v1.Artist
	(*Album)(nil),                // 2: catalog.v1.Album
	(*Playlist)(nil),             // 3: catalog.v1.Playlist
	(*GetTrackByIDRequest)(nil),  // 4: catalog.v1.GetTrackByIDRequest
	(*GetTrackByIDResponse)(nil), // 5: catalog.v1.GetTrackByIDResponse
	(*TrackExistsRequest)(nil),   // 6: catalog.v1.TrackExistsRequest
	(*TrackExistsResponse)(nil),  // 7: catalog.v1.TrackExistsResponse
	(*SearchTrackResponse)(nil),  // 8: catalog.v1.SearchTrackResponse
	(*SearchTrackRequest)(nil),   // 9: catalog.v1.SearchTrackRequest
	(*SearchArtistRequest)(nil),  // 10: catalog.v1.SearchArtistRequest
	(*SearchArtistResponse)(nil), // 11: catalog.v1.SearchArtistResponse
}
var file_proto_catalog_v1_catalog_proto_depIdxs = []int32{
	2,  // 0: catalog.v1.Artist.albums:type_name -> catalog.v1.Album
	0,  // 1: catalog.v1.Album.tracks:type_name -> catalog.v1.Track
	0,  // 2: catalog.v1.Playlist.tracks:type_name -> catalog.v1.Track
	0,  // 3: catalog.v1.SearchTrackResponse.tracks:type_name -> catalog.v1.Track
	1,  // 4: catalog.v1.SearchArtistResponse.artists:type_name -> catalog.v1.Artist
	4,  // 5: catalog.v1.CatalogService.GetTrackByID:input_type -> catalog.v1.GetTrackByIDRequest
	6,  // 6: catalog.v1.CatalogService.TrackExists:input_type -> catalog.v1.TrackExistsRequest
	9,  // 7: catalog.v1.CatalogService.SearchTrack:input_type -> catalog.v1.SearchTrackRequest
	10, // 8: catalog.v1.CatalogService.SearchArtist:input_type -> catalog.v1.SearchArtistRequest
	5,  // 9: catalog.v1.CatalogService.GetTrackByID:output_type -> catalog.v1.GetTrackByIDResponse
	7,  // 10: catalog.v1.CatalogService.TrackExists:output_type -> catalog.v1.TrackExistsResponse
	8,  // 11: catalog.v1.CatalogService.SearchTrack:output_type -> catalog.v1.SearchTrackResponse
	11, // 12: catalog.v1.CatalogService.SearchArtist:output_type -> catalog.v1.SearchArtistResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_catalog_v1_catalog_proto_init() }
func file_proto_catalog_v1_catalog_proto_init() {
	if File_proto_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_v1_catalog_proto_rawDesc), len(file_proto_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_v1_catalog_proto = out.File
	file_proto_catalog_v1_catalog_proto_goTypes = nil
	file_proto_catalog_v1_catalog_proto_depIdxs = nil
}
