// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/catalog/v1/catalog.proto

package catalogv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_GetTrackByID_FullMethodName = "/catalog.v1.CatalogService/GetTrackByID"
	CatalogService_TrackExists_FullMethodName  = "/catalog.v1.CatalogService/TrackExists"
	CatalogService_SearchTrack_FullMethodName  = "/catalog.v1.CatalogService/SearchTrack"
	CatalogService_SearchArtist_FullMethodName = "/catalog.v1.CatalogService/SearchArtist"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	GetTrackByID(ctx context.Context, in *GetTrackByIDRequest, opts ...grpc.CallOption) (*GetTrackByIDResponse, error)
	TrackExists(ctx context.Context, in *TrackExistsRequest, opts ...grpc.CallOption) (*TrackExistsResponse, error)
	SearchTrack(ctx context.Context, in *SearchTrackRequest, opts ...grpc.CallOption) (*SearchTrackResponse, error)
	SearchArtist(ctx context.Context, in *SearchArtistRequest, opts ...grpc.CallOption) (*SearchArtistResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetTrackByID(ctx context.Context, in *GetTrackByIDRequest, opts ...grpc.CallOption) (*GetTrackByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackByIDResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetTrackByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) TrackExists(ctx context.Context, in *TrackExistsRequest, opts ...grpc.CallOption) (*TrackExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackExistsResponse)
	err := c.cc.Invoke(ctx, CatalogService_TrackExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchTrack(ctx context.Context, in *SearchTrackRequest, opts ...grpc.CallOption) (*SearchTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTrackResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchArtist(ctx context.Context, in *SearchArtistRequest, opts ...grpc.CallOption) (*SearchArtistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchArtistResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	GetTrackByID(context.Context, *GetTrackByIDRequest) (*GetTrackByIDResponse, error)
	TrackExists(context.Context, *TrackExistsRequest) (*TrackExistsResponse, error)
	SearchTrack(context.Context, *SearchTrackRequest) (*SearchTrackResponse, error)
	SearchArtist(context.Context, *SearchArtistRequest) (*SearchArtistResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) GetTrackByID(context.Context, *GetTrackByIDRequest) (*GetTrackByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrackByID not implemented")
}
func (UnimplementedCatalogServiceServer) TrackExists(context.Context, *TrackExistsRequest) (*TrackExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackExists not implemented")
}
func (UnimplementedCatalogServiceServer) SearchTrack(context.Context, *SearchTrackRequest) (*SearchTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTrack not implemented")
}
func (UnimplementedCatalogServiceServer) SearchArtist(context.Context, *SearchArtistRequest) (*SearchArtistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArtist not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_GetTrackByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetTrackByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetTrackByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetTrackByID(ctx, req.(*GetTrackByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_TrackExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).TrackExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_TrackExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).TrackExists(ctx, req.(*TrackExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchTrack(ctx, req.(*SearchTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchArtist(ctx, req.(*SearchArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrackByID",
			Handler:    _CatalogService_GetTrackByID_Handler,
		},
		{
			MethodName: "TrackExists",
			Handler:    _CatalogService_TrackExists_Handler,
		},
		{
			MethodName: "SearchTrack",
			Handler:    _CatalogService_SearchTrack_Handler,
		},
		{
			MethodName: "SearchArtist",
			Handler:    _CatalogService_SearchArtist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/catalog/v1/catalog.proto",
}
