// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// структуры для клиента
type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	TrackName     string                 `protobuf:"bytes,2,opt,name=track_name,json=trackName,proto3" json:"track_name,omitempty"`
	ArtistUuid    string                 `protobuf:"bytes,3,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	ArtistName    string                 `protobuf:"bytes,4,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	AlbumUuid     string                 `protobuf:"bytes,5,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	AlbumName     string                 `protobuf:"bytes,6,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	Explicit      bool                   `protobuf:"varint,7,opt,name=explicit,proto3" json:"explicit,omitempty"`
	DurationMs    int32                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

func (x *Track) GetTrackName() string {
	if x != nil {
		return x.TrackName
	}
	return ""
}

func (x *Track) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *Track) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *Track) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

func (x *Track) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

func (x *Track) GetExplicit() bool {
	if x != nil {
		return x.Explicit
	}
	return false
}

func (x *Track) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type LightTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	TrackName     string                 `protobuf:"bytes,2,opt,name=track_name,json=trackName,proto3" json:"track_name,omitempty"`
	Explicit      bool                   `protobuf:"varint,3,opt,name=explicit,proto3" json:"explicit,omitempty"`
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightTrack) Reset() {
	*x = LightTrack{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightTrack) ProtoMessage() {}

func (x *LightTrack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightTrack.ProtoReflect.Descriptor instead.
func (*LightTrack) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *LightTrack) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

func (x *LightTrack) GetTrackName() string {
	if x != nil {
		return x.TrackName
	}
	return ""
}

func (x *LightTrack) GetExplicit() bool {
	if x != nil {
		return x.Explicit
	}
	return false
}

func (x *LightTrack) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Artist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistUuid    string                 `protobuf:"bytes,1,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	ArtistName    string                 `protobuf:"bytes,2,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artist) Reset() {
	*x = Artist{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Artist) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *Artist) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumUuid     string                 `protobuf:"bytes,1,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	ArtistUuid    string                 `protobuf:"bytes,2,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	AlbumName     string                 `protobuf:"bytes,3,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Album) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

func (x *Album) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *Album) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

func (x *Album) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type LightAlbum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumUuid     string                 `protobuf:"bytes,1,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	AlbumName     string                 `protobuf:"bytes,2,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightAlbum) Reset() {
	*x = LightAlbum{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightAlbum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightAlbum) ProtoMessage() {}

func (x *LightAlbum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightAlbum.ProtoReflect.Descriptor instead.
func (*LightAlbum) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *LightAlbum) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

func (x *LightAlbum) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

func (x *LightAlbum) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistUuid  string                 `protobuf:"bytes,1,opt,name=playlist_uuid,json=playlistUuid,proto3" json:"playlist_uuid,omitempty"`
	PlaylistName  string                 `protobuf:"bytes,2,opt,name=playlist_name,json=playlistName,proto3" json:"playlist_name,omitempty"`
	OwnerUuid     string                 `protobuf:"bytes,3,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
	OwnerName     string                 `protobuf:"bytes,4,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Tracks        []*Track               `protobuf:"bytes,5,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *Playlist) GetPlaylistUuid() string {
	if x != nil {
		return x.PlaylistUuid
	}
	return ""
}

func (x *Playlist) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

func (x *Playlist) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *Playlist) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Playlist) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type GetArtistTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistUuid    string                 `protobuf:"bytes,1,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistTracksRequest) Reset() {
	*x = GetArtistTracksRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistTracksRequest) ProtoMessage() {}

func (x *GetArtistTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistTracksRequest.ProtoReflect.Descriptor instead.
func (*GetArtistTracksRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetArtistTracksRequest) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *GetArtistTracksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetArtistTracksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetArtistTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistTracks  []*LightTrack          `protobuf:"bytes,1,rep,name=artist_tracks,json=artistTracks,proto3" json:"artist_tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistTracksResponse) Reset() {
	*x = GetArtistTracksResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistTracksResponse) ProtoMessage() {}

func (x *GetArtistTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistTracksResponse.ProtoReflect.Descriptor instead.
func (*GetArtistTracksResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetArtistTracksResponse) GetArtistTracks() []*LightTrack {
	if x != nil {
		return x.ArtistTracks
	}
	return nil
}

type GetAlbumTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumUuid     string                 `protobuf:"bytes,1,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumTracksRequest) Reset() {
	*x = GetAlbumTracksRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumTracksRequest) ProtoMessage() {}

func (x *GetAlbumTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumTracksRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumTracksRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *GetAlbumTracksRequest) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

type GetAlbumTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LightTrack    []*LightTrack          `protobuf:"bytes,1,rep,name=light_track,json=lightTrack,proto3" json:"light_track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumTracksResponse) Reset() {
	*x = GetAlbumTracksResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumTracksResponse) ProtoMessage() {}

func (x *GetAlbumTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumTracksResponse.ProtoReflect.Descriptor instead.
func (*GetAlbumTracksResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *GetAlbumTracksResponse) GetLightTrack() []*LightTrack {
	if x != nil {
		return x.LightTrack
	}
	return nil
}

type GetArtistAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistUuid    string                 `protobuf:"bytes,1,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistAlbumsRequest) Reset() {
	*x = GetArtistAlbumsRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistAlbumsRequest) ProtoMessage() {}

func (x *GetArtistAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistAlbumsRequest.ProtoReflect.Descriptor instead.
func (*GetArtistAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *GetArtistAlbumsRequest) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *GetArtistAlbumsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetArtistAlbumsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetArtistAlbumsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistAlbums  []*LightAlbum          `protobuf:"bytes,1,rep,name=artist_albums,json=artistAlbums,proto3" json:"artist_albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistAlbumsResponse) Reset() {
	*x = GetArtistAlbumsResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistAlbumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistAlbumsResponse) ProtoMessage() {}

func (x *GetArtistAlbumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistAlbumsResponse.ProtoReflect.Descriptor instead.
func (*GetArtistAlbumsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *GetArtistAlbumsResponse) GetArtistAlbums() []*LightAlbum {
	if x != nil {
		return x.ArtistAlbums
	}
	return nil
}

type GetTrackByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackByIDRequest) Reset() {
	*x = GetTrackByIDRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackByIDRequest) ProtoMessage() {}

func (x *GetTrackByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTrackByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *GetTrackByIDRequest) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

// так как это будет использоваться только для стриминг сервиса,
// оставил только то, что ему нужно: путь до файла, длительность
// и explicit (для проверки возрастных ограничений)
type GetTrackByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DurationMs    int32                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Explicit      bool                   `protobuf:"varint,3,opt,name=explicit,proto3" json:"explicit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackByIDResponse) Reset() {
	*x = GetTrackByIDResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackByIDResponse) ProtoMessage() {}

func (x *GetTrackByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTrackByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *GetTrackByIDResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetTrackByIDResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *GetTrackByIDResponse) GetExplicit() bool {
	if x != nil {
		return x.Explicit
	}
	return false
}

type TrackExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackExistsRequest) Reset() {
	*x = TrackExistsRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackExistsRequest) ProtoMessage() {}

func (x *TrackExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackExistsRequest.ProtoReflect.Descriptor instead.
func (*TrackExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *TrackExistsRequest) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

type TrackExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackExistsResponse) Reset() {
	*x = TrackExistsResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackExistsResponse) ProtoMessage() {}

func (x *TrackExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackExistsResponse.ProtoReflect.Descriptor instead.
func (*TrackExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *TrackExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type SearchTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTrackResponse) Reset() {
	*x = SearchTrackResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTrackResponse) ProtoMessage() {}

func (x *SearchTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTrackResponse.ProtoReflect.Descriptor instead.
func (*SearchTrackResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *SearchTrackResponse) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type SearchTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackName     string                 `protobuf:"bytes,1,opt,name=track_name,json=trackName,proto3" json:"track_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTrackRequest) Reset() {
	*x = SearchTrackRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTrackRequest) ProtoMessage() {}

func (x *SearchTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTrackRequest.ProtoReflect.Descriptor instead.
func (*SearchTrackRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *SearchTrackRequest) GetTrackName() string {
	if x != nil {
		return x.TrackName
	}
	return ""
}

func (x *SearchTrackRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchTrackRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistName    string                 `protobuf:"bytes,1,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtistRequest) Reset() {
	*x = SearchArtistRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtistRequest) ProtoMessage() {}

func (x *SearchArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtistRequest.ProtoReflect.Descriptor instead.
func (*SearchArtistRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *SearchArtistRequest) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *SearchArtistRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchArtistRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchArtistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artists       []*Artist              `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtistResponse) Reset() {
	*x = SearchArtistResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtistResponse) ProtoMessage() {}

func (x *SearchArtistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtistResponse.ProtoReflect.Descriptor instead.
func (*SearchArtistResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *SearchArtistResponse) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

type GetPlaylistByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistUuid  string                 `protobuf:"bytes,1,opt,name=playlist_uuid,json=playlistUuid,proto3" json:"playlist_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistByIDRequest) Reset() {
	*x = GetPlaylistByIDRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistByIDRequest) ProtoMessage() {}

func (x *GetPlaylistByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistByIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *GetPlaylistByIDRequest) GetPlaylistUuid() string {
	if x != nil {
		return x.PlaylistUuid
	}
	return ""
}

type GetPlaylistByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistByIDResponse) Reset() {
	*x = GetPlaylistByIDResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistByIDResponse) ProtoMessage() {}

func (x *GetPlaylistByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistByIDResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{21}
}

func (x *GetPlaylistByIDResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

type GetArtistByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistUuid    string                 `protobuf:"bytes,1,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistByIDRequest) Reset() {
	*x = GetArtistByIDRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistByIDRequest) ProtoMessage() {}

func (x *GetArtistByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistByIDRequest.ProtoReflect.Descriptor instead.
func (*GetArtistByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *GetArtistByIDRequest) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

type GetArtistByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *Artist                `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistByIDResponse) Reset() {
	*x = GetArtistByIDResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistByIDResponse) ProtoMessage() {}

func (x *GetArtistByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistByIDResponse.ProtoReflect.Descriptor instead.
func (*GetArtistByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{23}
}

func (x *GetArtistByIDResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type GetAlbumByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumUuid     string                 `protobuf:"bytes,1,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumByIDRequest) Reset() {
	*x = GetAlbumByIDRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumByIDRequest) ProtoMessage() {}

func (x *GetAlbumByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{24}
}

func (x *GetAlbumByIDRequest) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

type GetAlbumByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumByIDResponse) Reset() {
	*x = GetAlbumByIDResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumByIDResponse) ProtoMessage() {}

func (x *GetAlbumByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumByIDResponse.ProtoReflect.Descriptor instead.
func (*GetAlbumByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{25}
}

func (x *GetAlbumByIDResponse) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

type AddArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistName    string                 `protobuf:"bytes,1,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArtistRequest) Reset() {
	*x = AddArtistRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArtistRequest) ProtoMessage() {}

func (x *AddArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArtistRequest.ProtoReflect.Descriptor instead.
func (*AddArtistRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{26}
}

func (x *AddArtistRequest) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

type AddArtistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *Artist                `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArtistResponse) Reset() {
	*x = AddArtistResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArtistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArtistResponse) ProtoMessage() {}

func (x *AddArtistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArtistResponse.ProtoReflect.Descriptor instead.
func (*AddArtistResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{27}
}

func (x *AddArtistResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type AddAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistUuid    string                 `protobuf:"bytes,1,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	AlbumName     string                 `protobuf:"bytes,2,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAlbumRequest) Reset() {
	*x = AddAlbumRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAlbumRequest) ProtoMessage() {}

func (x *AddAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAlbumRequest.ProtoReflect.Descriptor instead.
func (*AddAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{28}
}

func (x *AddAlbumRequest) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *AddAlbumRequest) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

type AddAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAlbumResponse) Reset() {
	*x = AddAlbumResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAlbumResponse) ProtoMessage() {}

func (x *AddAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAlbumResponse.ProtoReflect.Descriptor instead.
func (*AddAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{29}
}

func (x *AddAlbumResponse) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

type AddTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackName     string                 `protobuf:"bytes,1,opt,name=track_name,json=trackName,proto3" json:"track_name,omitempty"`
	ArtistUuid    string                 `protobuf:"bytes,2,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	AlbumUuid     string                 `protobuf:"bytes,3,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	Explicit      bool                   `protobuf:"varint,4,opt,name=explicit,proto3" json:"explicit,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	DurationMs    int32                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackRequest) Reset() {
	*x = AddTrackRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackRequest) ProtoMessage() {}

func (x *AddTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackRequest.ProtoReflect.Descriptor instead.
func (*AddTrackRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{30}
}

func (x *AddTrackRequest) GetTrackName() string {
	if x != nil {
		return x.TrackName
	}
	return ""
}

func (x *AddTrackRequest) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *AddTrackRequest) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

func (x *AddTrackRequest) GetExplicit() bool {
	if x != nil {
		return x.Explicit
	}
	return false
}

func (x *AddTrackRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddTrackRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type AddTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	TrackName     string                 `protobuf:"bytes,2,opt,name=track_name,json=trackName,proto3" json:"track_name,omitempty"`
	ArtistUuid    string                 `protobuf:"bytes,3,opt,name=artist_uuid,json=artistUuid,proto3" json:"artist_uuid,omitempty"`
	AlbumUuid     string                 `protobuf:"bytes,4,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	Explicit      bool                   `protobuf:"varint,5,opt,name=explicit,proto3" json:"explicit,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	DurationMs    int32                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackResponse) Reset() {
	*x = AddTrackResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackResponse) ProtoMessage() {}

func (x *AddTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackResponse.ProtoReflect.Descriptor instead.
func (*AddTrackResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{31}
}

func (x *AddTrackResponse) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

func (x *AddTrackResponse) GetTrackName() string {
	if x != nil {
		return x.TrackName
	}
	return ""
}

func (x *AddTrackResponse) GetArtistUuid() string {
	if x != nil {
		return x.ArtistUuid
	}
	return ""
}

func (x *AddTrackResponse) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

func (x *AddTrackResponse) GetExplicit() bool {
	if x != nil {
		return x.Explicit
	}
	return false
}

func (x *AddTrackResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddTrackResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type AlbumTrackInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumTrackInput) Reset() {
	*x = AlbumTrackInput{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumTrackInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumTrackInput) ProtoMessage() {}

func (x *AlbumTrackInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumTrackInput.ProtoReflect.Descriptor instead.
func (*AlbumTrackInput) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{32}
}

func (x *AlbumTrackInput) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

func (x *AlbumTrackInput) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type AddTracksToAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumUuid     string                 `protobuf:"bytes,1,opt,name=album_uuid,json=albumUuid,proto3" json:"album_uuid,omitempty"`
	Tracks        []*AlbumTrackInput     `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTracksToAlbumRequest) Reset() {
	*x = AddTracksToAlbumRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTracksToAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTracksToAlbumRequest) ProtoMessage() {}

func (x *AddTracksToAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTracksToAlbumRequest.ProtoReflect.Descriptor instead.
func (*AddTracksToAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{33}
}

func (x *AddTracksToAlbumRequest) GetAlbumUuid() string {
	if x != nil {
		return x.AlbumUuid
	}
	return ""
}

func (x *AddTracksToAlbumRequest) GetTracks() []*AlbumTrackInput {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type AddTracksToAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTracksToAlbumResponse) Reset() {
	*x = AddTracksToAlbumResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTracksToAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTracksToAlbumResponse) ProtoMessage() {}

func (x *AddTracksToAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTracksToAlbumResponse.ProtoReflect.Descriptor instead.
func (*AddTracksToAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{34}
}

type IncrementListenedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUuid     string                 `protobuf:"bytes,1,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementListenedRequest) Reset() {
	*x = IncrementListenedRequest{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementListenedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementListenedRequest) ProtoMessage() {}

func (x *IncrementListenedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementListenedRequest.ProtoReflect.Descriptor instead.
func (*IncrementListenedRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{35}
}

func (x *IncrementListenedRequest) GetTrackUuid() string {
	if x != nil {
		return x.TrackUuid
	}
	return ""
}

type IncrementListenedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementListenedResponse) Reset() {
	*x = IncrementListenedResponse{}
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementListenedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementListenedResponse) ProtoMessage() {}

func (x *IncrementListenedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_v1_catalog_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementListenedResponse.ProtoReflect.Descriptor instead.
func (*IncrementListenedResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{36}
}

var File_proto_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"\x82\x02\n" +
	"\x05Track\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\x12\x1d\n" +
	"\n" +
	"track_name\x18\x02 \x01(\tR\ttrackName\x12\x1f\n" +
	"\vartist_uuid\x18\x03 \x01(\tR\n" +
	"artistUuid\x12\x1f\n" +
	"\vartist_name\x18\x04 \x01(\tR\n" +
	"artistName\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x05 \x01(\tR\talbumUuid\x12\x1d\n" +
	"\n" +
	"album_name\x18\x06 \x01(\tR\talbumName\x12\x1a\n" +
	"\bexplicit\x18\a \x01(\bR\bexplicit\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x05R\n" +
	"durationMs\"\x87\x01\n" +
	"\n" +
	"LightTrack\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\x12\x1d\n" +
	"\n" +
	"track_name\x18\x02 \x01(\tR\ttrackName\x12\x1a\n" +
	"\bexplicit\x18\x03 \x01(\bR\bexplicit\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\"J\n" +
	"\x06Artist\x12\x1f\n" +
	"\vartist_uuid\x18\x01 \x01(\tR\n" +
	"artistUuid\x12\x1f\n" +
	"\vartist_name\x18\x02 \x01(\tR\n" +
	"artistName\"\x85\x01\n" +
	"\x05Album\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x01 \x01(\tR\talbumUuid\x12\x1f\n" +
	"\vartist_uuid\x18\x02 \x01(\tR\n" +
	"artistUuid\x12\x1d\n" +
	"\n" +
	"album_name\x18\x03 \x01(\tR\talbumName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"i\n" +
	"\n" +
	"LightAlbum\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x01 \x01(\tR\talbumUuid\x12\x1d\n" +
	"\n" +
	"album_name\x18\x02 \x01(\tR\talbumName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\xbd\x01\n" +
	"\bPlaylist\x12#\n" +
	"\rplaylist_uuid\x18\x01 \x01(\tR\fplaylistUuid\x12#\n" +
	"\rplaylist_name\x18\x02 \x01(\tR\fplaylistName\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x03 \x01(\tR\townerUuid\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x04 \x01(\tR\townerName\x12)\n" +
	"\x06tracks\x18\x05 \x03(\v2\x11.catalog.v1.TrackR\x06tracks\"g\n" +
	"\x16GetArtistTracksRequest\x12\x1f\n" +
	"\vartist_uuid\x18\x01 \x01(\tR\n" +
	"artistUuid\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"V\n" +
	"\x17GetArtistTracksResponse\x12;\n" +
	"\rartist_tracks\x18\x01 \x03(\v2\x16.catalog.v1.LightTrackR\fartistTracks\"6\n" +
	"\x15GetAlbumTracksRequest\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x01 \x01(\tR\talbumUuid\"Q\n" +
	"\x16GetAlbumTracksResponse\x127\n" +
	"\vlight_track\x18\x01 \x03(\v2\x16.catalog.v1.LightTrackR\n" +
	"lightTrack\"g\n" +
	"\x16GetArtistAlbumsRequest\x12\x1f\n" +
	"\vartist_uuid\x18\x01 \x01(\tR\n" +
	"artistUuid\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"V\n" +
	"\x17GetArtistAlbumsResponse\x12;\n" +
	"\rartist_albums\x18\x01 \x03(\v2\x16.catalog.v1.LightAlbumR\fartistAlbums\"4\n" +
	"\x13GetTrackByIDRequest\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\"g\n" +
	"\x14GetTrackByIDResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x05R\n" +
	"durationMs\x12\x1a\n" +
	"\bexplicit\x18\x03 \x01(\bR\bexplicit\"3\n" +
	"\x12TrackExistsRequest\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\"-\n" +
	"\x13TrackExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"@\n" +
	"\x13SearchTrackResponse\x12)\n" +
	"\x06tracks\x18\x01 \x03(\v2\x11.catalog.v1.TrackR\x06tracks\"a\n" +
	"\x12SearchTrackRequest\x12\x1d\n" +
	"\n" +
	"track_name\x18\x01 \x01(\tR\ttrackName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"d\n" +
	"\x13SearchArtistRequest\x12\x1f\n" +
	"\vartist_name\x18\x01 \x01(\tR\n" +
	"artistName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"D\n" +
	"\x14SearchArtistResponse\x12,\n" +
	"\aartists\x18\x01 \x03(\v2\x12.catalog.v1.ArtistR\aartists\"=\n" +
	"\x16GetPlaylistByIDRequest\x12#\n" +
	"\rplaylist_uuid\x18\x01 \x01(\tR\fplaylistUuid\"K\n" +
	"\x17GetPlaylistByIDResponse\x120\n" +
	"\bplaylist\x18\x01 \x01(\v2\x14.catalog.v1.PlaylistR\bplaylist\"7\n" +
	"\x14GetArtistByIDRequest\x12\x1f\n" +
	"\vartist_uuid\x18\x01 \x01(\tR\n" +
	"artistUuid\"C\n" +
	"\x15GetArtistByIDResponse\x12*\n" +
	"\x06artist\x18\x01 \x01(\v2\x12.catalog.v1.ArtistR\x06artist\"4\n" +
	"\x13GetAlbumByIDRequest\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x01 \x01(\tR\talbumUuid\"?\n" +
	"\x14GetAlbumByIDResponse\x12'\n" +
	"\x05album\x18\x01 \x01(\v2\x11.catalog.v1.AlbumR\x05album\"3\n" +
	"\x10AddArtistRequest\x12\x1f\n" +
	"\vartist_name\x18\x01 \x01(\tR\n" +
	"artistName\"?\n" +
	"\x11AddArtistResponse\x12*\n" +
	"\x06artist\x18\x01 \x01(\v2\x12.catalog.v1.ArtistR\x06artist\"Q\n" +
	"\x0fAddAlbumRequest\x12\x1f\n" +
	"\vartist_uuid\x18\x01 \x01(\tR\n" +
	"artistUuid\x12\x1d\n" +
	"\n" +
	"album_name\x18\x02 \x01(\tR\talbumName\";\n" +
	"\x10AddAlbumResponse\x12'\n" +
	"\x05album\x18\x01 \x01(\v2\x11.catalog.v1.AlbumR\x05album\"\xc1\x01\n" +
	"\x0fAddTrackRequest\x12\x1d\n" +
	"\n" +
	"track_name\x18\x01 \x01(\tR\ttrackName\x12\x1f\n" +
	"\vartist_uuid\x18\x02 \x01(\tR\n" +
	"artistUuid\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x03 \x01(\tR\talbumUuid\x12\x1a\n" +
	"\bexplicit\x18\x04 \x01(\bR\bexplicit\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x05R\n" +
	"durationMs\"\xe1\x01\n" +
	"\x10AddTrackResponse\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\x12\x1d\n" +
	"\n" +
	"track_name\x18\x02 \x01(\tR\ttrackName\x12\x1f\n" +
	"\vartist_uuid\x18\x03 \x01(\tR\n" +
	"artistUuid\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x04 \x01(\tR\talbumUuid\x12\x1a\n" +
	"\bexplicit\x18\x05 \x01(\bR\bexplicit\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x05R\n" +
	"durationMs\"L\n" +
	"\x0fAlbumTrackInput\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\"m\n" +
	"\x17AddTracksToAlbumRequest\x12\x1d\n" +
	"\n" +
	"album_uuid\x18\x01 \x01(\tR\talbumUuid\x123\n" +
	"\x06tracks\x18\x02 \x03(\v2\x1b.catalog.v1.AlbumTrackInputR\x06tracks\"\x1a\n" +
	"\x18AddTracksToAlbumResponse\"9\n" +
	"\x18IncrementListenedRequest\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\x01 \x01(\tR\ttrackUuid\"\x1b\n" +
	"\x19IncrementListenedResponse2\x90\x06\n" +
	"\x0eCatalogService\x12Q\n" +
	"\fGetTrackByID\x12\x1f.catalog.v1.GetTrackByIDRequest\x1a .catalog.v1.GetTrackByIDResponse\x12N\n" +
	"\vTrackExists\x12\x1e.catalog.v1.TrackExistsRequest\x1a\x1f.catalog.v1.TrackExistsResponse\x12N\n" +
	"\vSearchTrack\x12\x1e.catalog.v1.SearchTrackRequest\x1a\x1f.catalog.v1.SearchTrackResponse\x12T\n" +
	"\rGetArtistByID\x12 .catalog.v1.GetArtistByIDRequest\x1a!.catalog.v1.GetArtistByIDResponse\x12Q\n" +
	"\fSearchArtist\x12\x1f.catalog.v1.SearchArtistRequest\x1a .catalog.v1.SearchArtistResponse\x12Z\n" +
	"\x0fGetArtistAlbums\x12\".catalog.v1.GetArtistAlbumsRequest\x1a#.catalog.v1.GetArtistAlbumsResponse\x12Z\n" +
	"\x0fGetArtistTracks\x12\".catalog.v1.GetArtistTracksRequest\x1a#.catalog.v1.GetArtistTracksResponse\x12Q\n" +
	"\fGetAlbumByID\x12\x1f.catalog.v1.GetAlbumByIDRequest\x1a .catalog.v1.GetAlbumByIDResponse\x12W\n" +
	"\x0eGetAlbumTracks\x12!.catalog.v1.GetAlbumTracksRequest\x1a\".catalog.v1.GetAlbumTracksResponse2\xae\x03\n" +
	"\x13CatalogWriteService\x12H\n" +
	"\tAddArtist\x12\x1c.catalog.v1.AddArtistRequest\x1a\x1d.catalog.v1.AddArtistResponse\x12E\n" +
	"\bAddAlbum\x12\x1b.catalog.v1.AddAlbumRequest\x1a\x1c.catalog.v1.AddAlbumResponse\x12E\n" +
	"\bAddTrack\x12\x1b.catalog.v1.AddTrackRequest\x1a\x1c.catalog.v1.AddTrackResponse\x12]\n" +
	"\x10AddTracksToAlbum\x12#.catalog.v1.AddTracksToAlbumRequest\x1a$.catalog.v1.AddTracksToAlbumResponse\x12`\n" +
	"\x11IncrementListened\x12$.catalog.v1.IncrementListenedRequest\x1a%.catalog.v1.IncrementListenedResponseB)Z'privy_stream/proto/catalog/v1;catalogv1b\x06proto3"

var (
	file_proto_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_v1_catalog_proto_rawDescData []byte
)

func file_proto_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_v1_catalog_proto_rawDesc), len(file_proto_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_v1_catalog_proto_rawDescData
}

var file_proto_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_catalog_v1_catalog_proto_goTypes = []any{
	(*Track)(nil),                     // 0: catalog.v1.Track
	(*LightTrack)(nil),                // 1: catalog.v1.LightTrack
	(*Artist)(nil),                    // 2: catalog.v1.Artist
	(*Album)(nil),                     // 3: catalog.v1.Album
	(*LightAlbum)(nil),                // 4: catalog.v1.LightAlbum
	(*Playlist)(nil),                  // 5: catalog.v1.Playlist
	(*GetArtistTracksRequest)(nil),    // 6: catalog.v1.GetArtistTracksRequest
	(*GetArtistTracksResponse)(nil),   // 7: catalog.v1.GetArtistTracksResponse
	(*GetAlbumTracksRequest)(nil),     // 8: catalog.v1.GetAlbumTracksRequest
	(*GetAlbumTracksResponse)(nil),    // 9: catalog.v1.GetAlbumTracksResponse
	(*GetArtistAlbumsRequest)(nil),    // 10: catalog.v1.GetArtistAlbumsRequest
	(*GetArtistAlbumsResponse)(nil),   // 11: catalog.v1.GetArtistAlbumsResponse
	(*GetTrackByIDRequest)(nil),       // 12: catalog.v1.GetTrackByIDRequest
	(*GetTrackByIDResponse)(nil),      // 13: catalog.v1.GetTrackByIDResponse
	(*TrackExistsRequest)(nil),        // 14: catalog.v1.TrackExistsRequest
	(*TrackExistsResponse)(nil),       // 15: catalog.v1.TrackExistsResponse
	(*SearchTrackResponse)(nil),       // 16: catalog.v1.SearchTrackResponse
	(*SearchTrackRequest)(nil),        // 17: catalog.v1.SearchTrackRequest
	(*SearchArtistRequest)(nil),       // 18: catalog.v1.SearchArtistRequest
	(*SearchArtistResponse)(nil),      // 19: catalog.v1.SearchArtistResponse
	(*GetPlaylistByIDRequest)(nil),    // 20: catalog.v1.GetPlaylistByIDRequest
	(*GetPlaylistByIDResponse)(nil),   // 21: catalog.v1.GetPlaylistByIDResponse
	(*GetArtistByIDRequest)(nil),      // 22: catalog.v1.GetArtistByIDRequest
	(*GetArtistByIDResponse)(nil),     // 23: catalog.v1.GetArtistByIDResponse
	(*GetAlbumByIDRequest)(nil),       // 24: catalog.v1.GetAlbumByIDRequest
	(*GetAlbumByIDResponse)(nil),      // 25: catalog.v1.GetAlbumByIDResponse
	(*AddArtistRequest)(nil),          // 26: catalog.v1.AddArtistRequest
	(*AddArtistResponse)(nil),         // 27: catalog.v1.AddArtistResponse
	(*AddAlbumRequest)(nil),           // 28: catalog.v1.AddAlbumRequest
	(*AddAlbumResponse)(nil),          // 29: catalog.v1.AddAlbumResponse
	(*AddTrackRequest)(nil),           // 30: catalog.v1.AddTrackRequest
	(*AddTrackResponse)(nil),          // 31: catalog.v1.AddTrackResponse
	(*AlbumTrackInput)(nil),           // 32: catalog.v1.AlbumTrackInput
	(*AddTracksToAlbumRequest)(nil),   // 33: catalog.v1.AddTracksToAlbumRequest
	(*AddTracksToAlbumResponse)(nil),  // 34: catalog.v1.AddTracksToAlbumResponse
	(*IncrementListenedRequest)(nil),  // 35: catalog.v1.IncrementListenedRequest
	(*IncrementListenedResponse)(nil), // 36: catalog.v1.IncrementListenedResponse
}
var file_proto_catalog_v1_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.v1.Playlist.tracks:type_name -> catalog.v1.Track
	1,  // 1: catalog.v1.GetArtistTracksResponse.artist_tracks:type_name -> catalog.v1.LightTrack
	1,  // 2: catalog.v1.GetAlbumTracksResponse.light_track:type_name -> catalog.v1.LightTrack
	4,  // 3: catalog.v1.GetArtistAlbumsResponse.artist_albums:type_name -> catalog.v1.LightAlbum
	0,  // 4: catalog.v1.SearchTrackResponse.tracks:type_name -> catalog.v1.Track
	2,  // 5: catalog.v1.SearchArtistResponse.artists:type_name -> catalog.v1.Artist
	5,  // 6: catalog.v1.GetPlaylistByIDResponse.playlist:type_name -> catalog.v1.Playlist
	2,  // 7: catalog.v1.GetArtistByIDResponse.artist:type_name -> catalog.v1.Artist
	3,  // 8: catalog.v1.GetAlbumByIDResponse.album:type_name -> catalog.v1.Album
	2,  // 9: catalog.v1.AddArtistResponse.artist:type_name -> catalog.v1.Artist
	3,  // 10: catalog.v1.AddAlbumResponse.album:type_name -> catalog.v1.Album
	32, // 11: catalog.v1.AddTracksToAlbumRequest.tracks:type_name -> catalog.v1.AlbumTrackInput
	12, // 12: catalog.v1.CatalogService.GetTrackByID:input_type -> catalog.v1.GetTrackByIDRequest
	14, // 13: catalog.v1.CatalogService.TrackExists:input_type -> catalog.v1.TrackExistsRequest
	17, // 14: catalog.v1.CatalogService.SearchTrack:input_type -> catalog.v1.SearchTrackRequest
	22, // 15: catalog.v1.CatalogService.GetArtistByID:input_type -> catalog.v1.GetArtistByIDRequest
	18, // 16: catalog.v1.CatalogService.SearchArtist:input_type -> catalog.v1.SearchArtistRequest
	10, // 17: catalog.v1.CatalogService.GetArtistAlbums:input_type -> catalog.v1.GetArtistAlbumsRequest
	6,  // 18: catalog.v1.CatalogService.GetArtistTracks:input_type -> catalog.v1.GetArtistTracksRequest
	24, // 19: catalog.v1.CatalogService.GetAlbumByID:input_type -> catalog.v1.GetAlbumByIDRequest
	8,  // 20: catalog.v1.CatalogService.GetAlbumTracks:input_type -> catalog.v1.GetAlbumTracksRequest
	26, // 21: catalog.v1.CatalogWriteService.AddArtist:input_type -> catalog.v1.AddArtistRequest
	28, // 22: catalog.v1.CatalogWriteService.AddAlbum:input_type -> catalog.v1.AddAlbumRequest
	30, // 23: catalog.v1.CatalogWriteService.AddTrack:input_type -> catalog.v1.AddTrackRequest
	33, // 24: catalog.v1.CatalogWriteService.AddTracksToAlbum:input_type -> catalog.v1.AddTracksToAlbumRequest
	35, // 25: catalog.v1.CatalogWriteService.IncrementListened:input_type -> catalog.v1.IncrementListenedRequest
	13, // 26: catalog.v1.CatalogService.GetTrackByID:output_type -> catalog.v1.GetTrackByIDResponse
	15, // 27: catalog.v1.CatalogService.TrackExists:output_type -> catalog.v1.TrackExistsResponse
	16, // 28: catalog.v1.CatalogService.SearchTrack:output_type -> catalog.v1.SearchTrackResponse
	23, // 29: catalog.v1.CatalogService.GetArtistByID:output_type -> catalog.v1.GetArtistByIDResponse
	19, // 30: catalog.v1.CatalogService.SearchArtist:output_type -> catalog.v1.SearchArtistResponse
	11, // 31: catalog.v1.CatalogService.GetArtistAlbums:output_type -> catalog.v1.GetArtistAlbumsResponse
	7,  // 32: catalog.v1.CatalogService.GetArtistTracks:output_type -> catalog.v1.GetArtistTracksResponse
	25, // 33: catalog.v1.CatalogService.GetAlbumByID:output_type -> catalog.v1.GetAlbumByIDResponse
	9,  // 34: catalog.v1.CatalogService.GetAlbumTracks:output_type -> catalog.v1.GetAlbumTracksResponse
	27, // 35: catalog.v1.CatalogWriteService.AddArtist:output_type -> catalog.v1.AddArtistResponse
	29, // 36: catalog.v1.CatalogWriteService.AddAlbum:output_type -> catalog.v1.AddAlbumResponse
	31, // 37: catalog.v1.CatalogWriteService.AddTrack:output_type -> catalog.v1.AddTrackResponse
	34, // 38: catalog.v1.CatalogWriteService.AddTracksToAlbum:output_type -> catalog.v1.AddTracksToAlbumResponse
	36, // 39: catalog.v1.CatalogWriteService.IncrementListened:output_type -> catalog.v1.IncrementListenedResponse
	26, // [26:40] is the sub-list for method output_type
	12, // [12:26] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_catalog_v1_catalog_proto_init() }
func file_proto_catalog_v1_catalog_proto_init() {
	if File_proto_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_v1_catalog_proto_rawDesc), len(file_proto_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_v1_catalog_proto = out.File
	file_proto_catalog_v1_catalog_proto_goTypes = nil
	file_proto_catalog_v1_catalog_proto_depIdxs = nil
}
